
SurvosThemesSimpleSearchBundle:
    resource: "@SurvosThemesSimpleSearchBundle/Controller/"
    type:     annotation
    prefix:   /simple

TobaccoPatentsBundle:
    resource: "@TobaccoPatentsBundle/Controller/"
    type:     annotation
    prefix:   /

AcmeDemoBundle:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation
    prefix:   /acme

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
